### ISSUE TITLE
Fails when YAML contains comments

### ISSUE THREAD

**Issue by agrrh** [microadam/drone-config-changeset-conditional#24]
When I add comment to my `.drone.yml`, plugin fails with:

```
Files changed: [ '.drone.yml' ]
(node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'kind' of null
    at parsedYaml.map (/app/plugin.js:49:12)
    at Array.map (<anonymous>)
    at app.post (/app/plugin.js:48:36)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
```

Issue reproduces with following YAML:

```
# Section 1                     <-- This causes plugin to fail
---

kind: pipeline
type: docker
name: foo

...

# Section 2                     <-- And this, too
---

kind: pipeline
type: docker
name: bar

...
```

**Comment by agrrh** [comment]
Probably would be fixed by #17
